Repository guguchecken/git_test, pull requests merged in 2022-07, with the labels that each got.

#35 Update test6.txt
  test6.txt
Labels: kind/bug

#31 Test66
  test5.txt
Labels: kind/bug

#34 Update main.txt
  main.txt
Labels: kind/bug

#41 Create test16.txt
  test16.txt
Labels: kind/bug

#44 Create test19.txt
  test19.txt
Labels: kind/feature

#43 Create test18.txt
  test18.txt
Labels: kind/enhancement

#42 Create test17.txt
  test17.txt
Labels: kind/bug

#47 Test20
  test20.txt
Labels: kind/bug

#48 Test21
  test21.txt
Labels: kind/bug

#49 Test22
  test22.txt
Labels: kind/bug

#50 Test23
  test23.txt
Labels: kind/bug

#53 Test32
  test32.txt
Labels: kind/api-change

#54 Test33
  test33.txt
Labels: kind/api-change
