Repository guguchecken/git_test, pull requests merged in 2022-08, with the labels that each got.

#52 Test31
  test31.txt
Labels: kind/bug

#51 Test30
  test30.txt
Labels: kind/enhancement

#57 Test40
  test40.txt
Labels: kind/bug

#58 Test41
  test41.txt
Labels: kind/documentation

#59 This is PR's title, which is now used here
  test30.txt
Labels: kind/api-change

#61 This is test1 title
  test1.txt
Labels: kind/feature

#62 This is Test2 title
  test1.txt
Labels: kind/feature

#63 This is test3 title
  test1.txt
Labels: kind/bug

#67 Test5
  test1.txt
Labels: kind/feature

#69 Test12
  src/test12.txt
Labels: kind/bug

#74 Test13
  src/test.txt
Labels: kind/test

#70 Test1
  src/test2.txt
Labels: kind/bug, do-not-merge/wip

#66 Test4
  test4.txt
Labels: kind/bug
